version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chochang8
      POSTGRES_DB: car_rental
